### PR TITLE
Handle recursive union types

### LINKED ISSUE #167: Stack overflow on master after type expression change
@ajalt Looks like there is an infinite loop in the new inference code related to type expressions (or possibly a latent bug in the reference system):

```
java.lang.StackOverflowError
	at org.elm.lang.core.resolve.scope.ModuleScope.getVisibleTypes(ModuleScope.kt:133)
	at org.elm.lang.core.resolve.reference.SimpleTypeReference.getCandidates(SimpleTypeReference.kt:20)
	at org.elm.lang.core.resolve.reference.SimpleTypeReference.resolveInner(SimpleTypeReference.kt:17)
	at org.elm.lang.core.resolve.reference.ElmReferenceCached$Resolver.resolve(ElmReferenceCached.kt:20)
	at org.elm.lang.core.resolve.reference.ElmReferenceCached$Resolver.resolve(ElmReferenceCached.kt:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:152)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:151)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:241)
	at org.elm.lang.core.resolve.reference.ElmReferenceCached.resolve(ElmReferenceCached.kt:15)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:159)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:155)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:131)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:56)
	at org.elm.lang.core.types.TypeExpression$typeDeclarationType$$inlined$map$lambda$1.invoke(TypeExpressionInference.kt:194)
	at org.elm.lang.core.types.TypeExpression$typeDeclarationType$$inlined$map$lambda$1.invoke(TypeExpressionInference.kt:56)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:149)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:654)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:684)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:675)
	at org.elm.lang.core.types.TypeExpression.typeDeclarationType(TypeExpressionInference.kt:194)
	at org.elm.lang.core.types.TypeExpression.beginTypeDeclarationInference(TypeExpressionInference.kt:72)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:162)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:155)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:131)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:56)
	at org.elm.lang.core.types.TypeExpression$typeDeclarationType$$inlined$map$lambda$1.invoke(TypeExpressionInference.kt:194)
	at org.elm.lang.core.types.TypeExpression$typeDeclarationType$$inlined$map$lambda$1.invoke(TypeExpressionInference.kt:56)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:149)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:654)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:684)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:675)
	at org.elm.lang.core.types.TypeExpression.typeDeclarationType(TypeExpressionInference.kt:194)
```

The file that this is blowing up in is quite large, and I haven't tried reducing it yet. Let me know if you need more than this stack trace.

### PR DESCRIPTION
**Pull request by ajalt**
Fixes #167

### CODE REVIEW

File: src/main/kotlin/org/elm/lang/core/types/TypeRendering.kt [hunk 1]
```diff
@@ -56,7 +62,7 @@ private fun StringBuilder.renderLink(refText: String, text: String, linkify: Boo
     else append(text)
 }
 
-
+/** Render a name or destructuring pattern to use a parameter for a function or case branch */
```
Comment (klazuka) [inline src/main/kotlin/org/elm/lang/core/types/TypeRendering.kt]: Yay! I was going to suggest a doc comment here on the last PR but I didn't want to quibble.

But now I _will_ quibble: should be "...to use _as_ a parameter for..."
