### PR TITLE
Complete full-program type unification

### LINKED ISSUE #362: Odd record field type inference behavior
The following code does not throw an error, despite `field` not being a field within Example.

```elm
type alias Example =
    { foo : Int }


testList : List Example
testList =
    [ { foo = 1 } ]


bar : List Example -> List Int
bar =
    List.map (\wrong -> wrong.field)


test1 : List Int
test1 =
    bar testList
```

similarly, these do not throw errors as well:
```elm
test2 : List Int
test2 =
    let
        bar2 =
            List.map (\wrong -> wrong.field) testList
    in
    bar2


test3 : List Int
test3 =
    List.map (\wrong -> wrong.field) testList
```

Thanks!

### LINKED ISSUE #363: Odd boxed type inference behavior
The following code does not produce an errors:
```elm
myVal : Maybe Int
myVal =
    Just 1


example : String
example =
    case myVal of
        Just anInt ->
            "A string added to " ++ anInt

        Nothing ->
            "foobar"
```

First experienced this when pattern matching on a `Maybe` within a record. E.g.
```elm
type alias Example = 
     { foo : Maybe Int }

myVal = 
    { foo = Just 42 }

example : String
example =
    case myVal.foo of
        Just anInt ->
            "A string added to " ++ anInt

        Nothing ->
            "foobar"
```

### LINKED ISSUE #381: Show type information while hoovering over symbols
It would be highly useful to **display type information in a tooltip** while **hovering over symbols** in the editor.  It would save valuable brain power and would help us benefit more from type inference.  It would also help fix compilation errors in the non-trivial cases.

Example of how this works in JetBrains Rider while editing F#:
fsharp-type-info-tooltip
Hovering over **h3**, mouse cursor is not visible on the screenshot above. Code is from [Giraffe's SampleApp](https://github.com/giraffe-fsharp/Giraffe/tree/master/samples/SampleApp/SampleApp).

### PR DESCRIPTION
**Pull request by ajalt**
This PR completes full-program unification, the last major milestone in the type inference project. With this PR, false-negatives on type inference are now considered bugs.

This PR also includes a number of optimizations. Despite doing more work to track types through scopes, type inference is now faster than it was before this PR.

Type inference now works in functions with more syntax errors. Notably, an error in a let-in expression or nested declaration won't stop type inference from running on the rest of the declarations, and errors in a case expression or branch won't stop earlier branches from being inferred.

Some type error diagnostic messages were also improved. For example, if the type of a case expression is mismatched, the error is now reported on the first case branch expression, rather then the entire case expression.

Untitled

I tested this on the following libraries and found no false-positives:

- `elm/browser`
- `elm/parser`
- `elm/url`
- `elm-explorations/test`
- `Malax/elmboy`
- `rtfeldman/elm-css`
- `opvasger/elm-devtools`
- `rtfeldman/elm-spa-example`
- `PowerLift`
- `cmditch/elm-ethereum`
- `w0rm/elm-mogee`
- `justgook/platformer`
- `r-k-b/tulars`

False negatives are harder to find tests for, so I went through all the examples in `elm/error-message-catalog`. None of the examples that are still valid in 0.19 result in false-negatives.

Note that this PR does _not_ implement case branch exhaustiveness checks. That's left as future work. There is also a known false-negative where in some cases using field accessor functions on records that don't contain the function's field will not result in an error. 

Fixes #381
Fixes #363
Fixes #362

### CODE REVIEW

**Comment by ajalt** [comment]
Note that this PR depends on #380. Once that branch is landed, I'll rebase this onto master.

File: src/main/kotlin/org/elm/lang/core/types/TypeReplacement.kt [hunk 1]
```diff
@@ -31,9 +34,24 @@ class TypeReplacement(
          * its vars are distinct, even though they share a name with vars from the previous
          * reference. If we use the cached tys, there's no way to distinguish between vars in one
          * call from another.
+         *
+         * Note that rigid vars are never freshened. In a function with an annotation like
+         * `f : (a -> b) -> a -> b`, every time you call the `(a -> b)` parameter within the body of
+         * `f`, the ty of `a` and `b` have to be the same.
```
Comment (ajalt) [inline src/main/kotlin/org/elm/lang/core/types/TypeReplacement.kt]: Did I mention var assignability was painful?

File: src/test/kotlin/org/elm/ide/inspections/TypeInferenceInspectionTest.kt [hunk 2]
```diff
@@ -1,1637 +0,0 @@
-package org.elm.ide.inspections
-
-class TypeInferenceInspectionTest : ElmInspectionsTestBase(ElmTypeInferenceInspection()) {
```
Comment (ajalt) [inline src/test/kotlin/org/elm/ide/inspections/TypeInferenceInspectionTest.kt]: I can recombine these if you'd like. IntelliJ chugs a bit when it's all a single file.

File: src/test/kotlin/org/elm/ide/inspections/inference/TypeDeclarationInspectionTest.kt [hunk 3]
```diff
@@ -7,7 +10,7 @@ class TypeDeclarationInspectionTest : ElmInspectionsTestBase(ElmTypeDeclarationI
 
     fun `test bad mutual self-recursion in type alias`() = checkByText("""
 <error descr="Infinite recursion">type alias A = B</error>
-<error descr="Infinite recursion">type alias B = A</error>
+type alias B = A
```
Comment (ajalt) [inline src/test/kotlin/org/elm/ide/inspections/inference/TypeDeclarationInspectionTest.kt]: The compiler only reports the first error, and not reporting both allows us to cache more inference results.

File: src/test/kotlin/org/elm/workspace/compiler/ElmBuildActionTest.kt [hunk 4]
```diff
@@ -49,7 +49,7 @@ class ElmBuildActionTest : ElmWorkspaceTestBase() {
         var succeeded = false
         with(project.messageBus.connect(testRootDisposable)) {
             subscribe(ElmBuildAction.ERRORS_TOPIC, object : ElmBuildAction.ElmErrorsListener {
-                override fun update(baseDirPath: Path, messages: List<ElmError>, filePathToCompile: String?) {
+                override fun update(baseDirPath: Path, messages: List<ElmError>, pathToCompile: String?) {
```
Comment (ajalt) [inline src/test/kotlin/org/elm/workspace/compiler/ElmBuildActionTest.kt]: This is just fixing a compile warning.

**Comment by klazuka** [comment]
> This PR completes full-program unification, the last major milestone in the type inference project

🔥 

> Despite doing more work to track types through scopes, type inference is now faster than it was before this PR

🔥 🔥 

> Type inference now works in functions with more syntax errors

🔥 🔥 🔥 

I don't know what more to say. 💯

File: src/main/kotlin/org/elm/ide/docs/ElmDocumentationProvider.kt [hunk 5]
```diff
@@ -55,19 +55,17 @@ class ElmDocumentationProvider : AbstractDocumentationProvider() {
 
 private fun documentationFor(decl: ElmFunctionDeclarationLeft): String? = buildString {
     val parent = decl.parent as? ElmValueDeclaration ?: return null
-    val typeAnnotation = parent.typeAnnotation
-
+    val ty = decl.findInference()?.ty
```
Comment (klazuka) [inline src/main/kotlin/org/elm/ide/docs/ElmDocumentationProvider.kt]: Nice

File: src/main/kotlin/org/elm/lang/core/types/TypeInference.kt [hunk 6]
```diff
@@ -206,6 +215,12 @@ private class InferenceScope(
         return isRecursive
     }
 
+    private fun replacedResult(ty: Ty): InferenceResult {
```
[the remark this answers is not in the document]
Comment (klazuka) [reply src/main/kotlin/org/elm/lang/core/types/TypeInference.kt]: Please add this as a comment in the source code as I was wondering whether it could/should have been used in other places.

File: src/main/kotlin/org/elm/lang/core/types/TypeInference.kt [hunk 7]
```diff
@@ -288,12 +304,22 @@ private class InferenceScope(
...
     private fun inferFunctionCall(expr: ElmFunctionCallExpr): Ty {
+        if (expr.hasErrors) return TyUnknown()
+
         val targetTy = inferAtom(expr.target)
         val arguments = expr.arguments.toList()
 
         // always infer the arguments so that they're added to expressionTypes
         val argTys = arguments.map { inferAtom(it) }
 
+        if (targetTy is TyVar) {
```
Comment (klazuka) [inline src/main/kotlin/org/elm/lang/core/types/TypeInference.kt]: When does this happen?

File: src/main/kotlin/org/elm/lang/core/types/TypeInference.kt (hunk 6 above)
[the remark this answers is not in the document]
Comment (klazuka) [reply src/main/kotlin/org/elm/lang/core/types/TypeInference.kt]: Maybe this function should be named "toTopLevelResult" to emphasize that it should only be used at the top-most inference scope (assuming that I understand this correctly).

File: src/main/kotlin/org/elm/lang/core/types/TypeInference.kt (hunk 7 above)
Comment (ajalt) [reply src/main/kotlin/org/elm/lang/core/types/TypeInference.kt]: When calling an unannotated parameter e.g. `foo f = f 123`

File: src/main/kotlin/org/elm/lang/core/types/TypeInference.kt [hunk 8]
```diff
@@ -86,11 +91,10 @@ private class InferenceScope(
...
 
         // If the assignee has any syntax errors, we don't run inference on it. Trying to resolve
-        // references in expressions that contain syntax errors can result in infinite recursion and
-        // surprising bugs.
-        // We don't currently infer recursive functions in order to avoid infinite loops in the inference.
-        if (checkRecursion(declaration) || assignee == null || PsiTreeUtil.hasErrorElements(assignee)) {
-            return InferenceResult(expressionTypes, diagnostics, TyUnknown())
+        // references in bodies when the parameters contain syntax errors can result in infinite
+        // recursion and surprising bugs.
+        if (checkRecursion(declaration) || assignee == null || assignee.hasErrors) {
```
[the remark this answers is not in the document]
Comment (ajalt) [reply src/main/kotlin/org/elm/lang/core/types/TypeInference.kt]: No, I should have left comment in.
