### PR TITLE
Cache the ElmProject SearchScope

### LINKED ISSUE #246: Cache the SearchScope for each ElmProject in the workspace
Constructing the `GlobalSearchScope` introduced by #244 is using a lot of CPU (and probably creating a lot of garbage). It's called very often, and it should be pretty easy to cache.

Here is what the CPU profiler found typing `foo = String.length "" ++ String.fromInt 99` at the bottom of PowerLift's `Main.elm` file (using IntelliJ's hidden "retype" feature). The top 3 are regressions.

screen shot 2019-02-02 at 4 39 09 pm

### PR DESCRIPTION
**Pull request by klazuka**
We were constructing this `ElmProject`-specific search scope value a lot, and it was dominating the CPU profiler traces. Now we cache 2 flavors of the search scope for each Elm project: 

1. just the project files
2. the project files plus the "tests" directory as well as the "test-dependencies".

Fixes #246

### CODE REVIEW

File: src/main/kotlin/org/elm/lang/core/lookup/ElmLookup.kt [hunk 1]
```diff
@@ -36,4 +55,76 @@ object ElmLookup {
...
+    fun searchScopeAt(loc: ClientLocation): GlobalSearchScope {
+        val elmProject = loc.elmProject ?: return GlobalSearchScope.EMPTY_SCOPE
+
+        /*
+        Build (and cache) the search scope based on the ClientLocation.
+
+        The cache will be invalidated whenever the Elm workspace changes
+        (e.g. the user modifies an `elm.json` file)
+
+        You might be wondering why we don't just construct the search scope when
```
Comment (klazuka) [inline src/main/kotlin/org/elm/lang/core/lookup/ElmLookup.kt]: @ajalt what do you think about this? Have I gone too far?

**Comment by klazuka** [comment]
Without caching: 
no caching

After adding the cache, it's much improved:
after adding cache
